### ISSUE TITLE
Contacts?

### ISSUE THREAD

**Issue by DonaldTsang** [Nonononoki/Hendroid#1]
Are there any ways of contacting the devs of this project (e.g. Discord, Telegram)? There are none in the readME when compared to Hentoid.

@AVnetWS/admin-team

**Comment by Nonononoki** [comment]
@DonaldTsang It's just me. I'm not really a developer of this app, more like a maintainer. If you have an issue with the app just create an issue here on Github.

**Comment by tryoutuser** [comment]
@Nonononoki hello, i just want to say thank you very much creating an alternative and better version of hentoid without tracking!! thank you!
