### ISSUE TITLE
I can't download nor read hentai

### ISSUE THREAD

**Issue by Ketchup1138** [Nonononoki/Hendroid#10]
1-At some websites download button doesn't getting whiter so I can't download it.
2-At some websites when I try to download it give me error.
3-Even when I download the hentai when I try to open it;
-Screen freeze but when I close and open the screen It's get better but The "Build-in Image viewer" only show the thumbnail not all the images
-When I tried other image viewers they also only show just the thumbnail and It's only use system image viewers not the others

The Websites not Download Hentais =
-Hitomi
-E-hentai
-Liscious.net
The Websites Crush at Download =
-Pururin
Error Code  =
[Error log : begin
Hentoid ver: 1.11.2.1 (147)
Error log for Please! Freeze! Please! #4 / Please!Freeze!Please! #4 G44222 [44222@Pururin] : 1 errors
2020-04-30T09:14:43.545 Image list - [Parsing] : End of input @ /44222/please-freeze-please-4
Error log : end]

**Comment by Nonononoki** [comment]
Error reports only when using latest version of the app. The F-droid version is often outdated because it's built by external servers outside of my control.

**Comment by Ketchup1138** [comment]
I did it now I just can't read hentais. I can read them only while downloading.
At normal whent I try to open it It's just show thumbnail and freeze.

**Comment by Ketchup1138** [comment]
Forget to say my phone meizu m6t and rooted. Is root bad for  this app?

**Comment by Nonononoki** [comment]
Root is fine.
I need more info:
Android version
A link to the gallery (you can open a book in browser with the icon on the upper right when in download view, then copy it here)

**Comment by Ketchup1138** [comment]
Android version 7.0
Marketieg Name M6T
Model M811H

https://nhentai.net/g/311793/ I can't open whatever i download

I tried get a lot of image viewer but Hendroid didn't see the at "Open With" part

I recorded a video about my problem and uploaded to Youtube, can I give link to you?

**Comment by Nonononoki** [comment]
Sure, post a link.
You can change the image viewer when swiping from the left edge, then tap on the cog icon. Go to Interfaces & Navigation and change image viewer.

**Comment by Ketchup1138** [comment]
https://youtu.be/DAG1e0ZvP3U

At image viewers just show 01.jpg

**Comment by Nonononoki** [comment]
Have you tried deleting the book and download it again?

**Comment by Ketchup1138** [comment]
Yes deleted and downloaded new books, same for every website.

-I changed where the storage it but same result
-I tried to save sd but same result
-Deleted and reinstall app but same result
-Tried an similar app everything was fine

Also checked books when I open from file manager all of them was working. I think something make app so heavy when I open "build-in image viewer".

Sometime while trying to close Hendroid it reopen again but everything work at  "build-in image viewer" and show it book whit all pages but i when i press back button It close app. I think It means It's working but something broken in background.

**Comment by Nonononoki** [comment]
Hm, I can't reproduce the issue, sorry. You could try to use Hentoid (https://github.com/avluis/Hentoid) and see if the bug is still there, and report it there if it is.

**Comment by Ketchup1138** [comment]
Hentoit working perfect even saw all books I downloaded from your app(which helps me when I want to use your app) but I wanted to use your app though :P I'll keep your app and install updates If bug goes away I'll let you know.

Thank you for helping 💜 Purple my favorite color by the way :D
