### ISSUE TITLE
[Feature suggestion] Support tor

### ISSUE THREAD

**Issue by kevinsmia1939** [Nonononoki/Hendroid#12]
Hi,
Do you know if it is possible to route traffic thought tor? This would circumvent some censorship by ISP.

Thanks.

**Comment by Nonononoki** [comment]
Sorry, no such feature planned unless there's a huge demand.
If you want to circumvent censorship use a VPN.

**Comment by kevinsmia1939** [comment]
> Sorry, no such feature planned unless there's a huge demand.
> If you want to circumvent censorship use a VPN.

Hello,
I case you are planning to implement this in the future.
Just some of my opinions of VPN vs Tor, Good VPN are not free, the free VPN usually keep logs and personal info while Tor might be slower, it is more private and can circumvent censorship. 

Thanks.
