### ISSUE TITLE
Light theme makes navbar's background white with white icons

### ISSUE THREAD

**Issue by MrHeating** [Nonononoki/Hendroid#14]
**Hendroid Version**: 1.12.1 F-Droid

**Device/Android Version**: Motorola Moto E⁴ Plus (nicklaus) (XT1771) / Android 7.1.1

**Issue details**: Turning on the light theme makes the navigation bar's background white, which is a problem on Andrid versions <8 because the buttons always stay white. It doesn't break the functionality, but makrs it unnecessary hard to see the buttons.

Here's an example:

![Screenshot_20200627-123508](https://user-images.githubusercontent.com/22666602/85920317-fb4afe80-b872-11ea-931e-f1b2c09b0cdb.png)

**Comment by Nonononoki** [comment]
Ah, thanks for the bug report. I appears that this display bug affects all Android versions. Will probably be gone next update.

**Comment by MrHeating** [comment]
I thoght that wouldn't be as much of a problem for newer versions (dark buttons) which is why I specified it.

On 29 June 2020 09:47:43 GMT+02:00, Nho Quy Dinh <notifications@github.com> wrote:
>Ah, thanks for the bug report. I appears that this display bug affects all Android versions. Will probably be gone next update.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nonononoki/Hendroid/issues/14#issuecomment-650992465
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Nonononoki** [comment]
@MrHeating Can you test on the latest version (https://github.com/Nonononoki/Hendroid/releases/tag/1.12.5)? Bug is now gone on my device.

**Comment by MrHeating** [comment]
Yet, it's gone now, tyvm.

On 17 August 2020 09:02:21 GMT+02:00, Nho Quy Dinh <notifications@github.com> wrote:
>@MrHeating Can you test on the latest version (https://github.com/Nonononoki/Hendroid/releases/tag/1.12.5)? Bug is now gone on my device.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Nonononoki/Hendroid/issues/14#issuecomment-674700410
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
