### ISSUE TITLE
Add "jump to page" for HentaiCafe

### ISSUE THREAD

**Issue by deliciouslytyped** [Nonononoki/Hendroid#16]
I'm not sure if I missed something but it would be great if there could be some "jump to page" functionality on HentaiCafe, because currently I have to go back to where I was page by page and that really sucks.

- or should I submit this issue upstream?

**Comment by deliciouslytyped** [comment]
Workaround in the meantime: browse to the page in firefox (e.g. by changing the page number in the url), and then use the "open with app" feature.

**Comment by Nonononoki** [comment]
For new features please create an issue upstream, I only do minor modifications and bugfixes

**Comment by deliciouslytyped** [comment]
upstream issue: https://github.com/avluis/Hentoid/issues/461
