### ISSUE TITLE
import metadata

### ISSUE THREAD

**Issue by Fehertukor** [Nonononoki/Hendroid#17]
->1.12.1
**Hendroid Version**:

**Device/Android Version**:
android version 8.0

The issue is:
Import metadata does not work.
The app can see the exported (and not modified .json file)
but it marks it as grey and does not do anything with it when I try to import it.
Reinstall did not help.
Tried from multiple locations too did not help.

**Comment by Nonononoki** [comment]
Try the app from upstream (https://github.com/avluis/Hentoid), if that doesn't work post your json file here

**Comment by Nonononoki** [comment]
Closing the issue because reporter is not responding
