### ISSUE TITLE
asmhentai parse error

### ISSUE THREAD

**Issue by tryoutuser** [Nonononoki/Hendroid#18]
**Hendroid Version**: v1.12.5

**Device/Android Version**: ASUS Zenfone Max Pro M1 8.1.0

**Issue details / Repro steps**: Try download one doujin from asmhentai, it moves to error tab and did not start download.

**Stack trace / LogCat**:
```ruby
Error log : begin
Hentoid ver: 1.12.5 (153)
Start : 2020-08-24T21:01:50.227Z
End : 2020-08-24T21:01:50.227Z (00:00)
-----
Error log for (doujin title here) [https:asmhentai.com157189@asmhentai] : 1 errors
2020-08-25T04:01:50.227 Image list - [Parsing] : length=6; index=-1 @ https://asmhentai.com/157189/
Error log : end
```

That's all what i can gather. I'm not even sure to report it here or in Hentoid github repo page.

**Comment by tryoutuser** [comment]
I saw the bugfix with new version release in Hentoid repo.

Waiting for your app update

**Comment by Nonononoki** [comment]
@tryoutuser Should be fixed now (https://github.com/Nonononoki/Hendroid/releases/tag/1.12.6)

**Comment by tryoutuser** [comment]
Epic!
