### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ArchBraab** [Nonononoki/Hendroid#2]
App crashes when choosing between the standard / custom storage location on a Google Pixel XL running Android 10.

Gave app permission to storage. Tried reinstalling without success.

**Comment by Nonononoki** [comment]
@ArchBraab Can you try the new version from the releases? https://github.com/Nonononoki/Hendroid/releases/tag/1.9.4.6

Note: It's not compatible with the F-droid version

**Comment by ArchBraab** [comment]
That fixed it!
