### ISSUE TITLE
[Feature Request] Custom Brightness

### ISSUE THREAD

**Issue by ghost** [Nonononoki/Hendroid#21]
To make it easier to read in low-light condition.

**Comment by Nonononoki** [comment]
What do you mean? If in a low light condition:
1. Reduce brightness of your device.
2. Use an app with a dark overlay like [RedMoon](https://f-droid.org/en/packages/com.jmstudios.redmoon/)

**Comment by iknownothingaboutcomputers** [comment]
RedMoon isn't battery friendly. The android manga reader app, Tachiyomi, has the feature I'm talking about so check it out someday. It's pretty nifty.

**Comment by Nonononoki** [comment]
Please request this feature upstream, as this fork is solely for minor adjustments: https://github.com/avluis/Hentoid
