### ISSUE TITLE
Stuck on splash screen on Android 10 (v1.12.9)

### ISSUE THREAD

**Issue by bluesaxman** [Nonononoki/Hendroid#23]
**Hendroid Version**:
1.12.9

**Device/Android Version**:
Moto G7 (river) / Linage OS 17.1 (Android 10)

**Issue details / Repro steps**:
I installed the app from the git release, 
I enabled storage permission for it, 
Then I opened the app,
It then sits at the splash screen and never goes any farther. Its not frozen, as I can rotate the screen and it will update the splash message, but it never loads anything else. 

**Stack trace / LogCat**:
I'm not really sure how to get this info...

**Comment by Nonononoki** [comment]
Have you tried an earlier version of the app?

**Comment by bluesaxman** [comment]
I originally tried with the current version on f-droid, that had the same issue. I also tried the version linked in https://github.com/Nonononoki/Hendroid/issues/2 version 1.9.4.6 That one didn't even make it to the splash screen and instead wouldl crash as soon as it was launched.

**Comment by Nonononoki** [comment]
Looks like you're the only one facing this problem. Try using the upstream app (https://github.com/avluis/Hentoid). If the problem persist create an issue there, because the devs there are more knowledgeable.

**Comment by bluesaxman** [comment]
Sounds good, It looks like it might be an upstream issue as upstream also gives me the same issue, I've opened the issue upstream, https://github.com/avluis/Hentoid/issues/693 Linking here incase you would like to have it as a reference, I'll close this issue here for now and watch that one instead.
