### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [Nonononoki/Hendroid#24]
We used to [remove some non-FOSS references](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.nonononoki.hendroid.yml#L129) and it built fine (accident?) but now...
```
> Task :app:compileReleaseJavaWithJavac
/home/vagrant/build/org.nonononoki.hendroid/app/src/main/java/me/devsaki/hentoid/util/GroupHelper.java:9: error: package com.google.firebase.crashlytics does not exist
import com.google.firebase.crashlytics.FirebaseCrashlytics;
                                      ^
/home/vagrant/build/org.nonononoki.hendroid/app/src/main/java/me/devsaki/hentoid/util/GroupHelper.java:104: error: cannot find symbol
            FirebaseCrashlytics crashlytics = FirebaseCrashlytics.getInstance();
            ^
  symbol:   class FirebaseCrashlytics
  location: class GroupHelper
/home/vagrant/build/org.nonononoki.hendroid/app/src/main/java/me/devsaki/hentoid/util/GroupHelper.java:104: error: cannot find symbol
            FirebaseCrashlytics crashlytics = FirebaseCrashlytics.getInstance();
                                              ^
  symbol:   variable FirebaseCrashlytics
  location: class GroupHelper
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
```
...maybe a gradle flavor is needed?

**Comment by Nonononoki** [comment]
Removed some analytics from upstream and it should build now in newest version: https://github.com/Nonononoki/Hendroid/releases/tag/1.13.1.1

**Comment by licaon-kter** [comment]
Is https://github.com/Nonononoki/Hendroid/commit/9989c91d6c0012a714219f16b6e8de38c380fab9 not available from other repos?

ReF: https://f-droid.org/wiki/index.php?title=org.nonononoki.hendroid/lastbuild_165&oldid=288582

/pls reopen

**Comment by Nonononoki** [comment]
@licaon-kter Looks like the library (a fork) for file decompression is not yet in JCenter. Created a release with upstream version, but it should support all formats except 7z on Android.

**Comment by Nonononoki** [comment]
F-droid has built the latest version, closing issue.
