### ISSUE TITLE
Unable to choose folder 

### ISSUE THREAD

**Issue by ribcrib** [Nonononoki/Hendroid#25]
**Hendroid Version**:
1.12.9

**Device/Android Version**:
Samsung Galaxy S20+

**Issue details / Repro steps**:
Recently upgraded to the new version of hendroid 1.12.9 from version 1.12.6.1. It's now requesting that I choose a new folder, but I am unable to because the previous folder located at /data/user/0/org.nonononoki.hendroid/app_/.Hendroid is not viewable from my Android device. I'm not able to select any other folder as I get an error that says "Please select an existing Hendroid folder. It's location is displayed on screen." Navigating to the visable folder in Android/data doesn't allow me to select it. 

**Stack trace / LogCat**:
```ruby
Can't get to settings to pull logs
```
![Screenshot_20201204-092520_Hendroid_1](https://user-images.githubusercontent.com/75489642/101182749-23097400-3614-11eb-9c50-87d3dee83353.jpg)

**Comment by Nonononoki** [comment]
Have you tried this with the latest 1.13.1 Version?

**Comment by ribcrib** [comment]
My install much have been corrupted through f-droid, because updating to 1.13.1 still brought me to this page. I uninstalled and reinstalled and that got it working but I lost my collection of stuff I'd saved which I wanted to avoid.
