### ISSUE TITLE
problems with e-hentai.org

### ISSUE THREAD

**Issue by Wyld-One** [Nonononoki/Hendroid#28]
**Hendroid Version**:
v 14.3 and 13.8

**Device/Android Version**:
runs ok on samsung galaxy s7
failes download on moto z3

**Issue details / Repro steps**:
on moto z3 tap/hold and download on bottom bar gives error message: can't download ... sorry~

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```
odd thing: works ok on older samsung s7 (android8.0.0,kernel 3.15.81

fails on moto z3: android 9, PDX29.84.51-11-7
note: other media repositories seem to work ok. just e-hentai.org broken. site mebtions problem with thier DNS 

note2: error kessage was from google play store HD version. f-droid version fails silently. play store vx.13.3, f-droid x.14.3

**Comment by Nonononoki** [comment]
Doesn't seem to be related to the app. Can you open a book on e-hentai in a browser (you can just use the open externally button)?

**Comment by Wyld-One** [comment]
e-hentai from multiple browswes works.

**Comment by Nonononoki** [comment]
I suggest you install the app from upstream (https://github.com/avluis/Hentoid) and report it there if the issue persist. Unfortunately I can't diagnose the problem.
