### ISSUE TITLE
Clear error on manual insertion of failed pages

### ISSUE THREAD

**Issue by Sanaki** [Nonononoki/Hendroid#3]
I have one issue from doujins.com that keeps popping a 403 on a single page. Presumably this is more of an issue with the site rather than the app. I've manually downloaded the missing page and inserted it, and it does show up correctly now, but despite being present the error is still shown and will not clear. It would be preferable for the error to automatically clear if the page is detected as already present when attempting to remedy the error.

EDIT: For now this can be achieved by editing the story's json, changing each applicable ERROR (as well as the final one if none remain) to DOWNLOADED, then going into advanced settings and rescanning the entire library. Not optimal, but it works.

**Comment by Nonononoki** [comment]
It seems that it's more complex than I thought. Maybe you can suggest it in the master project? https://github.com/avluis/Hentoid

**Comment by Sanaki** [comment]
Fair enough, thanks for taking a look.
