### ISSUE TITLE
Forking Gallery Cherry for F-droid

### ISSUE THREAD

**Issue by Flam3z** [Nonononoki/Hendroid#31]
Have you ever given thought to also fork [Gallery Cherry](https://github.com/RobbWatershed/GalleryCherry)  if it has any tracking/non-foss libraries, removing them and adding the app onto f-droid as well? 

By the way keep up the good work on providing the updates as soon as you can💜

**Comment by Nonononoki** [comment]
Sorry, I just don't have the time to maintain another project right now, especially a project I have no interest in.
