### ISSUE TITLE
App crashes when selecting downloads folder

### ISSUE THREAD

**Issue by prirai** [Nonononoki/Hendroid#32]
App crashes when selecting the "Select downloads Folder" button either at the beginning or in Preferences. More explained below.

**App Version**:
1.14.4 (167)

**Infinix X682C 10.0(N)  //Though not a device specific issue.**:

**Issue details / Repro steps**:
I had deleted the documentsui app unknowingly via adb. Two weeks back, when I installed Hendroid for the first time, this issue started. I didn't know exactly about the cause of the issue. I checked Hendroid's GitHub issues, no such found. ALthough I did find a similar unresolved issue on Hentoid's issues page.
Check this : https://github.com/avluis/Hentoid/issues/708
And this : https://github.com/avluis/Hentoid/issues/670
These people got the same issue that they didn't have the documents UI app. It's still unresolved.

**What I did**:
I took the log by adb but I don't know how to take the log of only a specific app. I don't think you would get anything in the log as DocumentsUI itself wasn't available.

I tried reinstalling DocumentsUI by adb. This time the DocumentsUI app crashed before opening. I saw that the MANAGE_DOCUMENTS permission wasn't enabled for this, which isn't the usual case. And I'm unable to provide the permissions myself as this is a signature protected privilege. 

**My suggestions : **
1.    If you could somehow change from documentsui to any other filemanager, this issue would be solved. 
2.    Otherwise, please provide an option to manually type the save folder
3.    Or you can provide a default save folder so that it's not mandatory to select through the documentsui app.

**Comment by Nonononoki** [comment]
Sorry, but the DocumentUI is a vital part of Android that should never be deleted. I suggest reinstalling the documentui app without adb, the second issue you mentioned was resolved by just installing the apk.

**Comment by prirai** [comment]
But the main issue is that I can't install it from other source as the signatures wouldn't match then. I tried installing the extracted system app too, but to no avail. 
I didn't know that it was very essential and didn't face any issue until now. Why don't you try to provide a default directory for downloads and then the user can change it accordingly if they want.
There are other apps too, but none of them relied heavily on a single app. They provide me with options as to which app I would choose.
Nevermind, I know this is a fork and there would be compatibility issues with the main branch if you make changes in the base.
Thanks a lot anyways.
