### ISSUE TITLE
Update F-Droid's app description?

### ISSUE THREAD

**Issue by ceptonit** [Nonononoki/Hendroid#34]
**Hendroid Version**: 1.14.7

From F-Droid's app description:
"Hendroid is an **ad-free** Doujinshi & H-Manga archiving and viewing app."

![Screenshot_20210611-170703_Hendroid_1](https://user-images.githubusercontent.com/12678743/121763849-a27d8000-cb2e-11eb-95a0-bf1bbaa5f5e7.png)

And maybe add "Ads" in the Anti-Features section?

I'm not against ads but at least it should be mentioned in the app description.

**Comment by Nonononoki** [comment]
Thanks, fixed it in latest release c3320c02d9b431c7229287fe1c03a10e770e1836
