### ISSUE TITLE
Toonily downloads have stopped working

### ISSUE THREAD

**Issue by dtrfa** [Nonononoki/Hendroid#35]
Happens with all downloads from toonily:

Error log : begin
Hentoid ver: 1.14.7 (168)
API: 30
Device: OnePlus9_EEA / LE2113
Start : 2021-06-12T08:37:25.195Z
End : 2021-06-12T08:37:25.195Z (00:00)
-----
Error log for ANZ [webtoon/anz/@Toonily] : 1 errors
2021-06-12T10:37:25.195 Image list - [Parsing] : No images have been found. Error = null @ webtoon/anz/
Error log : end

**Comment by Nonononoki** [comment]
Please report it upstream (https://github.com/avluis/Hentoid) so more users can benefit from it.
