### ISSUE TITLE
[Feature request]Multitab support

### ISSUE THREAD

**Issue by Thewisem** [Nonononoki/Hendroid#36]
**Hendroid Version**: 1.14.8

**Device/Android Version**:

**Issue details / Repro steps**: It would be helpful if you add support gor multitabs so to open multiple hentai and swipe between each of them. It could be an option on the top left corner. Soo it is helpful to keep tabs on multiple hentais

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment]
I see that you have already created a ticket upstream (https://github.com/avluis/Hentoid/issues/809). Changes will be merge to this fork when it has been added to upstream.
