### ISSUE TITLE
App shows ads, and forbids screenshots when setting is enabled.

### ISSUE THREAD

**Issue by Jenneke42** [Nonononoki/Hendroid#37]
**Hendroid Version**: 1.14.9

**Device/Android Version**: Pixel 4a/Android 11

**Issue details / Repro steps**: App shows ads in menu. (Alovoa dating app specifically). App also does not allow screenshots when 'Allow screenshots' setting is enabled. Reproduction: Update app beyond 1.14.4. All later versions show ads.

**Stack trace / LogCat**: N/A
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment]
Ads are intended (obviously), and does not violate any store rules.
Screenshot work if you just restart the app.

**Comment by Jenneke42** [comment]
Better change your Readme then.
![Untitled](https://user-images.githubusercontent.com/74267094/124364930-a6fefb00-dbf9-11eb-8a62-8e096a8b63de.png)

**Comment by Nonononoki** [comment]
Thanks, fixed it

**Comment by Layerex** [comment]
For anyone wondering how to get rid of advertisment: [Hentoid](https://github.com/avluis/Hentoid), which Hendroid is the fork of has the same feature set but no this antifeature. You may use it instead.
