### ISSUE TITLE
E-Hentai galleries cannot be downloaded

### ISSUE THREAD

**Issue by falloutapie** [Nonononoki/Hendroid#39]
**Hendroid Version**: ver 1.14.9

**Device/Android version**: Samsung Galaxy A20

**Issue details / Repro steps**:
There's no obvious mechanism to download galleries in E-Hentai. When I first used Hendroid, the download button would say the files couldn't be found, or something along those lines. Now, the download button remains greyed out, indicating the app doesn't know it's on a gallery page. Is E-Hentai no longer supported?

This could be related to the issue posted April 5th by Wyld-One. #28 
I followed the advice in that thread, and Hentoid doesn't have this issue, so there's no use reporting the bug to them. Maybe some of that code can be copied into this project.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment]
I applied a quick fix in the new release: https://github.com/Nonononoki/Hendroid/releases/tag/1.14.10.1
