### ISSUE TITLE
Hentai cafe parser and pururin don't work

### ISSUE THREAD

**Issue by Pahom-ka** [Nonononoki/Hendroid#4]
**Hendroid Version**: 1.10.1, 1.9.6

**Device/Android Version**: OnePlus 3t with lineage os 16 (android 9).

**Issue details / Repro steps**: try to add queues from this sites, image don't download.

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment]
@Pahom-ka 
I'm also Android 9 and see no such errors. Try to connect to another network, check your DNS and Adblockers, provide steps to reproduce and/or provide logcat and logs (logs can be found in the Hendroid folder)

**Comment by Pahom-ka** [comment]
Hmmm. It's really stranged. When i use my first vpn - hitomi, and any other sites work, but hentai cafe and pururin is don't work. When i  used Tor, i'm get same result. But now i use my second vpn account, this sites is worked. Hmmm....
 Thank you for your answer!)
