### ISSUE TITLE
I have a problem with pururin site

### ISSUE THREAD

**Issue by Bandy9000** [Nonononoki/Hendroid#40]
The site pururin is not working
I was on version 1.4.4 and update to 1.10.1 and still is not working

The android version is 11 and I'm using a Samsung Galaxy A20e SM-A202F/DS on version of one UI 3.1

The whole situation started yesterday and didn't observe it because of some problems with the internet
And is open the site from a already downloaded manga but i can't access anything i press the log in button and nothing just is trying to reach but can't is like reopening but is not loading
The page is giving a fast message that is saying that "No extra pages found"

**AND SORRY FOR THE PROBLEM THAT I FOUND**

**Comment by Nonononoki** [comment]
Pururin recently changed their domain, and no need to apologize for finding a problem. It's what open-source is all about :)
This release should fix it: https://github.com/Nonononoki/Hendroid/releases/tag/1.14.10.2
