### ISSUE TITLE
Again problems with pururin

### ISSUE THREAD

**Issue by Bandy9000** [Nonononoki/Hendroid#41]
Is a problem again with the site pururin and this affect the downloading of the content
First I tried to delete and reinstall the app and the problem is still there
The only thing I can say is the app is seeing that are pages missing and can't do anything

P.S Two bugs in a week is a new record for me 😅😅😅 and sorry for more work than you need to do 😂😭😂

**Comment by Nonononoki** [comment]
You're right, the problem is still there. I thought I could fix it quickly, but it seems more complicated. We'll have to way for upstream to fix it.

**Comment by Bandy9000** [comment]
The problem is not that big but you need to take your time is not a hurry

**Comment by runboy93** [comment]
Upstream fix
https://github.com/avluis/Hentoid/releases/tag/v1.14.11

**Comment by runboy93** [comment]
@Nonononoki

https://github.com/avluis/Hentoid/tree/v1.15.0

**Comment by Nonononoki** [comment]
https://github.com/Nonononoki/Hendroid/releases/tag/1.15.0
