### ISSUE TITLE
Pressing Hentai cafe stops the app

### ISSUE THREAD

**Issue by Thewisem** [Nonononoki/Hendroid#45]
**Hendroid Version**: 1.15.4

**Device/Android Version**: samsung galaxy Tab A android 7.1.1 Nougat

**Issue details / Repro steps**:

**Stack trace / LogCat**:
```ruby
paste stack trace and/or log here
```

**Comment by Nonononoki** [comment]
Ah yes, Hentai Cafe has been offline for a while. Removed entry in latest release: https://github.com/Nonononoki/Hendroid/releases/tag/1.15.5
