### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by Budiawan69** [Nonononoki/Hendroid#52]
**Hendroid Version**:1.15.18

**Device/Android Version**:works fine on vivo 1606 (y53) 

**Issue details / Repro steps**:hi im new to github, but i had some ideas for hendroid, please add feature that change app icon with its name to something, example calculator, so when your friends or someone didnt know that you installed this app

**Comment by Budiawan69** [comment]
The second idea is please add list tags for "Blocked Tags" feature, because im always forgor the tags that i dont like

**Comment by Nonononoki** [comment]
Please report big feature requests upstream to benefit a lot more users: https://github.com/avluis/Hentoid
