### ISSUE TITLE
Image Loading/Rendering Loop

### ISSUE THREAD

**Issue by Compleur** [Nonononoki/Hendroid#6]
**Hendroid Version**: 1.10.2

**Device/Android Version**:  Huawei P20 Lite / 8.0.0

**Issue details / Repro steps**: Opening a downloaded album with the built-in image viewer puts it into (what I can only describe it as) an image loading/reset render loop. The only way to stop this (from what I've tried) is to close the application from the recent apps list or force closing the application.

[gfycat link to relevant example clip](https://gfycat.com/negligiblebasickinkajou) 
[and source](https://giant.gfycat.com/NegligibleBasicKinkajou.webm).

Extra notes edit:
- The archive is located on the SD card.
- The built-in viewer has worked in previous versions (1.9.4).

**Comment by Nonononoki** [comment]
Can you give me the link of the album?

**Comment by Compleur** [comment]
Album appears to be irrelevant, it happens to happen on any album before update and ones downloaded after newest update. I can upload an album if you would like, but it seems to be the whole archive.

**Comment by Nonononoki** [comment]
I only need the link. If you tap on the button left next to the favorite icon (the heart one) you get to the album page. The button on the top right opens the album in a browser and copy that link here for further troubleshooting. 
I think it may be some weird image format that's not supported by the built-in image viewer.

**Comment by Compleur** [comment]
[nhentai.net/g/255662](https://nhentai.net/g/255662/) is an example if you want one.

Extra notes that I have added to the post:
- The archive is located on the SD card.
- The built-in viewer has worked in previous versions.

**Comment by Nonononoki** [comment]
I can confirm that it works for me using the latest version of Hendroid. Can you clear the cache or reinstall the application and try to open the album?

**Comment by Compleur** [comment]
Cleared cache and reinstalled to the latest version
[still gave me issues](https://gfycat.com/hairyshadowydarwinsfox)

**Comment by Nonononoki** [comment]
Hm, I really don't know how to reproduce the bug. Does the problem exist with another image viewer?

Since I can only do small bug fixes, you should try the master project (https://github.com/avluis/Hentoid) and report the issue there if it's still persists.

**Comment by Compleur** [comment]
Ok I'll check there.

**Comment by Compleur** [comment]
I'll close the issue since it's related to the other project

**Comment by Compleur** [comment]
Off topic question since I can't find another way without opening another issue page: were the trackers that you removed just from the sites, or were there ones in the app as well?

**Comment by Nonononoki** [comment]
@Compleur Trackers are only removed from the app (original Hentoid has Firebase dependency)

**Comment by Mrfiregem** [comment]
The upcoming Hentoid v1.11.0 release is supposed to fix this issue
