### ISSUE TITLE
app froze if you change display type from list to grid

### ISSUE THREAD

**Issue by t-phncs** [Nonononoki/Hendroid#61]
100 mangas
split into several groups
change display to grid
observed app stops responding

**Comment by Nonononoki** [comment]
Latest release should fix this issue: https://github.com/Nonononoki/Hendroid/releases/tag/v1.16.3

**Comment by Katzenwerfer** [comment]
Is there any estimate to when you are pushing that update to F-Droid ?
As of now the version listed there is still v1.16.2

**Comment by Nonononoki** [comment]
I don't publish anything to F-droid, it's an automatic process that I have no influence on.
