### ISSUE TITLE
Releases 1.11.0 and up not pushed to f-droid

### ISSUE THREAD

**Issue by RustyRing** [Nonononoki/Hendroid#8]
**Hendroid Version**: 1.10.2

**Issue details / Repro steps**: Versions 1.11.0 and 1.11.2 are not available on f-droid https://f-droid.org/en/packages/org.nonononoki.hendroid/ , perhaps this is on purpose and a new distribution channel is  used?

**Comment by Nonononoki** [comment]
It always takes up to three weeks to get the update on F-droid, afraid there's not much I can do about it, the process is automatic (and kinda random)

**Comment by licaon-kter** [comment]
If F-Droid could build: `ERROR: Found unknown maven repo 'https://dl.bintray.com/mikepenz/maven' at build.gradle`

What lib is not available in [a trusted repo](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99) ?

**Comment by Nonononoki** [comment]
@licaon-kter 
> If F-Droid could build: `ERROR: Found unknown maven repo 'https://dl.bintray.com/mikepenz/maven' at build.gradle`
> 
> What lib is not available in [a trusted repo](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99) or can't be build before building the app?
> 
> https://github.com/mikepenz/FastAdapter or https://github.com/mikepenz/Materialize (archived??) ?

Thanks for the info. Honestly, I don't really know haha - I just do a merge from original project and then remove the errors. Removing the repo did not cause any errors, I guess it's not really used? Anyway, I just created a new release, hope it goes through this time.

**Comment by Nonononoki** [comment]
Looks like latest version went through
